### ISSUE TITLE
PCL_SHARED_LIBS is always ON for Android

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl2#1]
See the code
https://github.com/PointCloudLibrary/pcl2/blob/f89677fb45e472f6d755731e931ffd8aed42e263/CMakeLists.txt#L22-L29

https://github.com/PointCloudLibrary/pcl2/blob/f89677fb45e472f6d755731e931ffd8aed42e263/cmake/pcl_options.cmake#L3-L4

Because `include(${PCL_SOURCE_DIR}/cmake/pcl_options.cmake)`
is executed after `set (PCL_SHARED_LIBS OFF)`, the statement
`option(PCL_SHARED_LIBS "Build shared libraries." ON)`
gives `PCL_SHARED_LIBS` a value `ON` regardless of the platform.

**Comment by taketwo** [comment]
Hi, this repository is abandoned, please use https://github.com/PointCloudLibrary/pcl.

**Comment by SergioRAgostinho** [comment]
I didn't know that. Is it ok if we merge his PR and then archive the repo? That will prevent opening issues and PRs on it.

**Comment by taketwo** [comment]
Sure, I don't mind merging that.
